version: '3.6'

services:

  elasticsearch:
    container_name: elastic_elasticsearch
    build:
      context: elasticsearch/
      dockerfile: elasticsearch.dockerfile
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - elk

  logstash:
    container_name: elastic_logstash
    build:
      context: logstash/
      dockerfile: logstash.dockerfile
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elk
      - app
    depends_on:
      - elasticsearch

  kibana:
    container_name: elastic_kibana
    build:
      context: kibana/
      dockerfile: kibana.dockerfile
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local

networks:
  app:
    external:
      name: "${APP_NETWORK_NAME}"
  elk:
    driver: bridge
